Develop dx
pnnl/copper pull request #103
Opened 2024-08-05 18:26 UTC by wanhanlong1130

new json file and new unit tests for DX.

2024-08-07 22:42 UTC, lymereJ commented
@wanhanlong1130 - Could you please do a reverse merge of the `develop` branch into your feature branch? It looks like there are a few conflicts.

2024-08-07 22:46 UTC, lymereJ commented
I've linked issues that this PR should address. Let's make sure that they're addressed before merging it!

2024-08-07 22:49 UTC, lymereJ commented
@aowabinr can you please review the library file brought over from #95? Thanks!

2024-08-07 22:49 UTC, lymereJ requested changes
@wanhanlong1130 - Could you please do a reverse merge of the develop branch into your feature branch? It looks like there are a few conflicts.

2024-08-07 23:36 UTC, lymereJ commented on copper/data/unitarydirectexpansion_curves.json
> +        "full_eff_ref_std": "ahri_341/361",
I think that we're using AHRI Standard 340/360.

2024-08-07 23:51 UTC, lymereJ commented on copper/data/unitarydirectexpansion_curves.json
> +        "compressor_speed": "constant/variable",
@aowabinr - Is this supposed to be variable capacity? Variable capacity compressors, I think, run a constant speed but have the capacity to modulate their capacity.

2024-08-12 15:40 UTC, wanhanlong1130 commented
> @wanhanlong1130 - Could you please do a reverse merge of the develop branch into your feature branch? It looks like there are a few conflicts.

Already done!

2024-08-12 15:43 UTC, wanhanlong1130 commented on copper/data/unitarydirectexpansion_curves.json
> +        "full_eff_ref_std": "ahri_341/361",
May need Aowabin to update from his side as well.

2024-08-12 21:37 UTC, lymereJ commented on copper/data/unitarydirectexpansion_curves.json
> +        "full_eff_ref_std": "ahri_341/361",
@aowabinr - FYI.

2024-08-12 21:40 UTC, lymereJ approved these changes

2024-08-14 22:52 UTC, merged