New ieer
pnnl/copper pull request #121
Opened 2024-10-30 22:18 UTC by wanhanlong1130

Add new IEER calculation and tests.

2024-11-01 21:26 UTC, lymereJ requested changes
Thanks! I think we need to make a few changes.

2024-11-01 21:26 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        compressor_stage=[0.3, 0.6],
Should it be plural? `compressor_stages`?

2024-11-01 21:26 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        compressor_stage=[0.3, 0.6],
I'm thinking that we probably either need to 1) check that they are provided in increasing order, or 2) sort them ourselves. For instance if a user provide `[0.5, 0.3, 0.8]` we would probably need it to be `[0.3, 0.5, 0.8]` for the rest of the code execution.

2024-11-01 21:26 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                and (reduced_plr[red_cap_num] < max(self.compressor_stage))
What if we have a three-stage unit and stage 2 (out of 3) is `= self.compressor_stage_input`?

You probably need something like that, just an example:
```python
interpolation = False
for stage_id, capacity_ratio  in enumerate(self.compressor_stage):
  if stage_id + 1 < len(self.compressor_stage):
    if self.compressor_stage[stage_id + 1] > reduced_plr[red_cap_num] > capacity_ratio:
      interpolation = True
    end
  end
end
    
  
```

2024-11-01 21:26 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +            """inner function to calculate reduced eer."""
We need a better docstring here: we need to document the arguments, provide a description, and document what is returned by the function. The formatting needs to be consistent with the other functions for the documentation to be generated.

2024-11-01 21:26 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                upper_value = None
It might be good to explicitly define the variable name. Maybe something like `lower_stage_load`, and `current_stage_load`?

2024-11-01 21:26 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                eer_reduced = (
If you look at example G4.3 in AHRI 340/360, the interpolation is based on the actual percent load, not just capacity ratio. I think that they're different.

If you have two stages: 100% and 50% of the rated (net) capacity. When you calculate the 75% EER at 81.5F OA DB, I think that you need to 1) calculate the actual net capacity of the unit for the larger stage and at the lower stage, 2) calculate and actual percent load where for the larger stage it would be the net capacity calculated in 1) divided by the rated net capacity, and for the lower capacity it would be the net capacity calculated in 1) divided by the rated net capacity * 0.5 (since the second stage is 50% of the rated net capacity. These would be the number to use in the interpolation.

2024-11-01 21:26 UTC, lymereJ commented on tests/test_unitarydirectexpansion.py
> +    def test_new_ieer(self):
To make sure that we're following the right approach, it would be nice to reproduce example G4.3 in this test. This would involve using dummy performance curves to get the same "test" results that they show in the example.

2024-11-04 17:52 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        compressor_stage=[0.3, 0.6],
Sure. Updated.

2024-11-04 17:54 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        compressor_stage=[0.3, 0.6],
Sure! It's not difficult to handle. I will update.

2024-11-04 18:00 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +            """inner function to calculate reduced eer."""
Will add! I thought it was inner function so didn't write it.

2024-11-04 18:01 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +                upper_value = None
Sure I will revise the names for 'values' to be more detailed.

2024-11-04 18:13 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +                eer_reduced = (
Did you mean using this load factor, not the EER_reduced at upper/lower stage?
![image](https://github.com/user-attachments/assets/5406858b-4b0c-44cf-97b0-c253af6327e9)
We can discuss more during the meeting.

2024-11-04 18:15 UTC, wanhanlong1130 commented on tests/test_unitarydirectexpansion.py
> +    def test_new_ieer(self):
Sure. I know that. It's just for current testing.

But, my question is, if we want to follow G4.3, do we need to add the curve files first? Should we use Table G12 or something else?

2024-11-04 18:16 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +                and (reduced_plr[red_cap_num] < max(self.compressor_stage))
did you mean we need to change > to >=? Not quite understand the logic difference between your approaches here with the one above.

2024-11-04 23:17 UTC, lymereJ commented on tests/test_unitarydirectexpansion.py
> +    def test_new_ieer(self):
You could just create curve objects on-the-fly like here: https://github.com/pnnl/copper/blob/develop/tests/test_unitarydirectexpansion.py#L86-L94

2024-11-04 23:19 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                and (reduced_plr[red_cap_num] < max(self.compressor_stage))
In the current proposed logic you seem ton compare the required part load ratio to the minimum and maximum compressor ratio. That works if you only have two stages, but if a particular case has three stages you need to know if you need to interpolate between stage 1 and 2, or between 2 and 3. What I proposed above _should_ do that, at least that's the idea.

2024-11-04 23:24 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                eer_reduced = (
Yes, see the **Actual Percent Load** column:
![image](https://github.com/user-attachments/assets/bfd16007-f5b4-4187-9f8e-f8bc5fdf515a)

2025-02-27 22:21 UTC, lymereJ commented
Closing, see #126.

2025-02-27 22:21 UTC, closed without merging