replaced the print statements with logging
pnnl/copper pull request #66
Opened 2022-12-13 01:37 UTC by ChristensenCode

Did a find all for print statements in the code and replaced them with python's logging module instead and added a constants file to store the common logging format.
This is related to issue #59

2023-01-04 05:11 UTC, lymereJ requested changes
@ChristensenCode - Sorry for the belated follow-up, I was out of the country for a few weeks. I've added a few comments. Please let me know if you think you can/want to address them this week, this is tied to a submission to the JOSS so I'd like to wrap it. I'll make the changes if you don't have time this week.

In addition to these comments, it would be nice to have a basic unit test for it.

2023-01-04 05:11 UTC, lymereJ commented on copper/constants.py
> +COOLING_LCT_551_591 = 7.0
This is not in related to logging so it should probably not included in this PR.

2023-01-04 05:11 UTC, lymereJ commented on copper/constants.py
> +LOGGING_FORMAT = "%(filename)s:%(lineno)d:%(levelname)s:%(message)s"
I think that it might be easier to move all `logging` setup to the `__init__.py` file.

2023-01-04 05:11 UTC, lymereJ commented on copper/constants.py
> +LOGGING_FORMAT = "%(filename)s:%(lineno)d:%(levelname)s:%(message)s"
Since most of the message are informative, I'm thinking that the format should probably be less file/code centric and be more general, perhaps something like `format='%(asctime)s - %(levelname)s - %(message)s'`.

2023-01-04 05:11 UTC, lymereJ commented on copper/constants.py
> +LOGGING_FORMAT = "%(filename)s:%(lineno)d:%(levelname)s:%(message)s"
We should probably output everything to stdout, so we'll need `stream=sys.stdout` in `basicConfig()`

2023-01-04 05:11 UTC, lymereJ commented on copper/curves.py
> +logging.basicConfig(format=LOGGING_FORMAT)
If we put all the logger configuration in `__init__.py` then we can just retrieve it using `logger = logging.getLogger(__name__)`

2023-01-05 22:40 UTC, ChristensenCode commented
@lymereJ My apologies for all the extra commits. I got turned around on what branch I was on and kept going back and forth.
I changed the format of the logging string and moved the basicconfig to the __init__. I also added a test for logging. I didn't see anything great (other than mocks or additional libraries) for testing the literal string being printed to the screen.

2023-01-06 06:00 UTC, lymereJ requested changes
@ChristensenCode - No worries! The test looks good enough to me, thanks for adding it. I left a few minor comments, once addressed I'll merge the PR.

2023-01-06 06:00 UTC, lymereJ commented on .gitignore
> +**/.vscode/**
Could you please revert these changes?

2023-01-06 06:00 UTC, lymereJ commented on copper/__init__.py
> +logging.basicConfig(format=LOGGING_FORMAT, stream=sys.stdout)
Could you please add `level=logging.INFO` at the end? That way we'll get everything displayed, we might want to change it later but for now it might be best.

2023-01-06 06:00 UTC, lymereJ commented on copper/constants.py
> +TODO: there are additional constants, but i haven't found them yet.
Maybe let's remove that TODO for now.

2023-01-06 10:10 UTC, ChristensenCode commented on .gitignore
> +**/.vscode/**
changes reverted

2023-01-06 10:10 UTC, ChristensenCode commented on copper/__init__.py
> +logging.basicConfig(format=LOGGING_FORMAT, stream=sys.stdout)
changed the logging level

2023-01-06 10:10 UTC, ChristensenCode commented on copper/constants.py
> +TODO: there are additional constants, but i haven't found them yet.
removed todo

2023-01-06 16:38 UTC, lymereJ commented
Thanks a lot for this effort, great addition to the code!

2023-01-06 16:39 UTC, lymereJ approved these changes

2023-01-06 16:39 UTC, merged