DX system development
pnnl/copper pull request #87
Opened 2024-02-28 19:11 UTC by wanhanlong1130

Add and check IEER calculation method for DX system; add DX json file, add unitary_dx class, add place holder for i_o process

2024-02-29 00:45 UTC, lymereJ requested changes
Thanks for this! I left some comments. After they've been addressed, I'll do another review, I have not yet looked at the IEER calculation very much.

2024-02-29 00:45 UTC, lymereJ commented on copper/unitary_dx.py
> +class Unitary_dx(Equipment):
According to [PEP 8](https://peps.python.org/pep-0008/#class-names), class names should use the CapWords convention so I think we should keep `UnitaryDX`.

2024-02-29 00:45 UTC, lymereJ commented on copper/data/unitary_dx_curves_template.json
> +{
Do we need this file?

2024-02-29 00:45 UTC, lymereJ commented on copper/data/load_file.py
> +import json
Let's rename the file to be something like `common.py` and put all the common functions. We also need to add the Sphinx documentation for the module.

2024-02-29 00:45 UTC, lymereJ commented on copper/data/load_file.py
> +def load_json_file(file_path):
Is this function actually used? I don't see where.

2024-02-29 00:45 UTC, lymereJ commented on copper/i_o_process.py
> +def output(ref, ref_unit, load, ect, idx, lwt, plr, cap_op, kwpton):
This seems to be an chiller specific function, it probably belongs in `chiller.py`.

2024-02-29 00:45 UTC, lymereJ commented on copper/i_o_process.py
> +def output(ref, ref_unit, load, ect, idx, lwt, plr, cap_op, kwpton):
We also need the Sphinx/Docstring comment to document the function.

2024-02-29 00:45 UTC, lymereJ commented on copper/unitary_dx.py
> +        part_eff_ref_std_alt="ahri_341/361",
I think that we probably want to default to the 340/360 which is the IP version of the standard.

2024-02-29 00:45 UTC, lymereJ commented on copper/unitary_dx.py
> +        model="simplified_bf",  # what is this?
We probably don't want to keep that comment.

2024-02-29 00:45 UTC, lymereJ commented on copper/unitary_dx.py
> +        if self.model == "X":
Let's use `simplified_bf` for the model used by EnergyPlus.

2024-02-29 00:45 UTC, lymereJ commented on copper/unitary_dx.py
> +    """
I assume that this should be deleted?

2024-02-29 00:45 UTC, lymereJ commented on copper/unitary_dx.py
> +    # print(X.get_ref_cond_flow_rate())
I understand that this might be used for development but we probably don't want to include it in the codebase since this will be used mostly as a module.

2024-02-29 00:45 UTC, lymereJ commented on copper/data/DX_oat.json
> +[
Is this the file generated by Yiting? We can't use it in this form so we should not include it in the code base.

2024-02-29 00:45 UTC, lymereJ commented on copper/data/efficiency.json
> +{
What is the purpose of this file? It does not seem to be used, if that's true, let's not include it in the code base.

2024-02-29 00:45 UTC, lymereJ commented on copper/data/equipment_references.json
> +                "AEW": [67,57],
We should try to use the same naming convention as the chiller info, that is a snake case conventions (that includes abbreviations).

2024-02-29 00:45 UTC, lymereJ commented on copper/curves.py
> +
This is already part of that function, so it should be deleted.

2024-02-29 00:45 UTC, lymereJ commented on copper/library.py
> +import copper.unitary_dx
To avoid the test failures, replace all import by:
```python
import json, inspect, copper
from copper.units import *
from copper.curves import *
```

2024-02-29 22:18 UTC, wanhanlong1130 commented on copper/curves.py
> +
Disagree; "" != None. In your recent dx template, you use "" instead of null. In the chiller template, you used null.

2024-02-29 22:21 UTC, wanhanlong1130 commented on copper/data/equipment_references.json
> +                "AEW": [67,57],
Did not get your point here. Did you mean change "unitary_dx" to "unitary_dx_equipment"? But you used "chiller" instead of "chiller equipment".

2024-02-29 22:23 UTC, wanhanlong1130 commented on copper/data/load_file.py
> +import json
Removed this file at this moment. Maybe we will need json import at another place.

2024-02-29 22:23 UTC, wanhanlong1130 commented on copper/data/unitary_dx_curves_template.json
> +{
Removed.

2024-02-29 22:26 UTC, wanhanlong1130 commented on copper/i_o_process.py
> +def output(ref, ref_unit, load, ect, idx, lwt, plr, cap_op, kwpton):
This function is just a place holder at this moment. Will develop more functions in the future - some for chillers, some for DX systems.

2024-02-29 22:33 UTC, wanhanlong1130 commented on copper/unitary_dx.py
> +class Unitary_dx(Equipment):
You used "unitary_dx" in the unitary_dx_curves.json. To make `eval("copper." + vals["eqp_type"].capitalize()).__init__` this works in the libary.py, I changed the name.

But, since you want to use "UnitaryDX" instead of "unitary_dx", I will update the json file.

2024-02-29 22:37 UTC, lymereJ commented on copper/curves.py
> +
Yes, we should be using null in the unitary DX equipment library and not make the changes in the code.

2024-02-29 22:40 UTC, lymereJ commented on copper/data/equipment_references.json
> +                "AEW": [67,57],
We use `ect` for the entering condenser temperature for chillers, not `ECT`. I assume that `AED` is air entering dry-bulb? We could go with something like `aed` or `aedb`. That way we use the same case convention.

2024-02-29 22:44 UTC, wanhanlong1130 commented on copper/data/equipment_references.json
> +                "AEW": [67,57],
I see.

2024-02-29 22:46 UTC, lymereJ commented on copper/unitary_dx.py
> +class Unitary_dx(Equipment):
We can definitely maker changes to the JSON files. The class name should follow the CapWords convention, perhaps we should use `UnitaryDirectExpansion`?

2024-03-25 21:37 UTC, lymereJ requested changes
Really sorry for the delay... Thanks for the revisions! I have a few more comments, a few specifically about the IEER calculation.

2024-03-25 21:37 UTC, lymereJ commented on copper/i_o_process.py
> +from copper.units import *
To be removed?

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +)  # TODO: add the library file.
Does the todo refer to the library file that includes the data collection?

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        may be move to equipment.py later
Let's move that into a TODO so it doesn't show up in the documentation.

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        AED = [
We should change the formatting of the variable to be consistent with others. So probably something like `aed`. Same for `AEW` => `aew`.

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        :param list fitlers: List of tuples containing the filter keys and values
Typo in the argument name `fitlers` instead of `filters`.

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        AED, AEW, ect, lct = self.get_rated_temperatures(alt)
See comment below about variable names.

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        """
The doc string seem to be missing some `param` description (`output_report` and `alt`).

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        AED, AEW, ect, lct = self.get_rated_temperatures()
See comment below about variable names.

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        # To DO check curvetypes
Do we still need this TODO?

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        eir = [eir_ref * item * eir_f_ff for item in eir_f_AEW_ect]
The EER that's used in the IEER calculations is documented in Section 6.2.3.2 of the [AHRI Standard 340/360-2022](https://www.ahrinet.org/system/files/2023-06/AHRI%20Standard%20340-360-2022%20%28I-P%29.pdf).

Based on that, I have a few comments:
- I don't see the load factor and degradation coefficients taken into account the EIR calculation, I think we should include it
- I see that the standards uses _net_ capacities which means that it includes the effect of the fan on the capacity. As you probably know, typically EnergyPlus deals with _gross_ capacities/efficiencies so we probably need an attribute that capture the unit's indoor fan power. Alternatively, we could have different sets of attributes to the `UnitaryDirectExpansion` class: one set for net efficiencies/capacities and one set of gross efficiencies/capacities, user could provide either and they would provide the latter we would calculate the net using the fan power attribute and use that in the IEER calculation.
- For the fan power attribute, would we ever have a case where we would have a single speed coil but a multi-speed fan? If so, the indoor fan power would have to be an array at the different percent load and the curves that are a function of flow fraction would have to be evaluated at the different air flows.

For reference, [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/StandardRatings.cc#L2124-L2178)'s how EnergyPlus handles it. It seems pretty much in line with the method shown in the standards. It might be good that, once we revised this function, we run tests against the latest version of EnergyPlus to see where we stand.

2024-03-25 21:37 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        ieer = 0.02 / eir[0] + 0.617 / eir[1] + 0.238 / eir[2] + 0.125 / eir[3]
I think you had suggested moving these coefficients out from the code to a reference file (`equipment_references.json`) I think that would be great.

2024-03-27 21:31 UTC, wanhanlong1130 commented on copper/i_o_process.py
> +from copper.units import *
A place holder here.

2024-03-27 21:32 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +)  # TODO: add the library file.
No. I just removed it.

2024-03-27 21:35 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        may be move to equipment.py later
It's already in equipment.py; I changed to use Equipment.get_eir_ref and removed this function in this file.

2024-03-27 21:37 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        AED = [
Updated

2024-03-27 21:37 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        :param list fitlers: List of tuples containing the filter keys and values
Corrected!

2024-03-27 21:40 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        """
Added.

2024-03-27 21:41 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        # To DO check curvetypes
Removed.

2024-03-27 21:51 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        ieer = 0.02 / eir[0] + 0.617 / eir[1] + 0.238 / eir[2] + 0.125 / eir[3]
Moved

2024-03-29 23:32 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                OutdoorUnitInletAirDryBulbTempReduced = OADBTempLowReducedCapacityTest
@wanhanlong1130 - the highlighted part corresponds to the Part-Load Rating Conditions of the standards (see Table 9).

2024-04-05 18:29 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +                OutdoorUnitInletAirDryBulbTempReduced = OADBTempLowReducedCapacityTest
Do you know where "0.444", "5", and "30" are from?

2024-04-05 19:40 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                OutdoorUnitInletAirDryBulbTempReduced = OADBTempLowReducedCapacityTest
The `5` and `30` is just from performing regression of the rated temperature for percent loads between 50 and 100%.

For the `0.444` I'm not sure, as long as it's below `0.5` it should be okay since the only rate temperature that doesn't follw the regression exactly is at 25% of load (65F).

2024-04-26 16:47 UTC, lymereJ requested changes
Thanks for the update, I think that we're almost there! A couple more comments.

2024-04-26 16:47 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        fan_power_mode = "fix_speed"
This should be an argument. Let's use `constant_speed` instead of `fix_speed`.

2024-04-26 16:47 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        cooling_coil_inlet_air_wet_bulb = 19.44
These should be pulled from the `equipment_references.json` file. Let's use `outdoor_unit...` instead of `out_door_unit...`

2024-04-26 16:47 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        fan_power = 7000
This should be an argument, not hard coded.

2024-04-26 16:47 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        # To Do, double check this naming
We probably don't need the comments here.

2024-04-26 16:47 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        self.condenser_type = "air"
This needs to be retrieved from the argument.

2024-04-26 16:47 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        return IEER
The naming convention of the variable should be the same as other variables for consistency. For instance, `DegradationCoeff` should be `degradation_coeff`.

2024-04-26 16:47 UTC, lymereJ commented on tests/test_unitarydirectexpansion.py
> +        cop_1 = round(5.981486044926383, 2)
`5.98`?

2024-04-26 16:47 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        DX_data = equipment_references[self.type][std][self.condenser_type]
`dx_data` instead of `DX_Data`.

2024-04-27 17:36 UTC, lymereJ commented on copper/data/equipment_references.json
> +            "cooling_coil_inlet_air_wet_bulb": 19.44
Seems like this should be `cooling_coil_inlet_air_wet_bulb_rated`, right?

2024-04-27 17:43 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +            self.ref_cap * tot_cap_temp_mod_fac * tot_cap_flow_mod_fac - self.fan_power
In EnergyPlus, users input gross coil capacities in models, but here, I think that users might want to provide the net capacity hence making `ref_cap` a net capacity so we would not need to do any conversion. Perhaps to be more clear we could have both `ref_net_cap` and `ref_gross_cap` (instead of just `ref_cap`). That way, users could provide one or the other and we could convert when applicable.

2024-04-27 17:44 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        rated_cop = self.full_eff
Same as above for the efficiency.

2024-04-27 17:47 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +            )
This would have to be modified as per discussion above. Note that `tot_cap_temp_mod_fac` is a gross capacity modifier, not net.

2024-04-27 17:49 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                eir = 0.0
We should probably log an warning or error message if this occurs as it is unexpected (instead of silently assuming and `eir` of 0). We use the `logging` library, there are examples in the codebase.

2024-04-27 17:57 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                eir = eir_temp_mod_fac * eir_flow_mod_fac / rated_cop
`rated_cop` here has to be the gross COP at rated conditions, not the net rated COP. Perhaps we should also have two sets of inputs to make sure we're using the correct one here.

2024-04-27 18:00 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +            elec_power_reduced_cap = (
In the standard, this is `C_D * (P_C + P_CD)` so the compressor and condenser section power adjusted for part load degradation. I feel like `elec_power_reduced_cap` doesn't clearly evoke that. Perhaps we could use `elec_power_degrad_gross`, `gross` to note that it excludes fan power, perhaps there's a better variable name to use.

2024-04-27 18:10 UTC, lymereJ commented
I took another look at the IEER calculation and made a few other comments, I think that we need to make a few more edits.

2024-04-27 18:36 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        fan_power=7000,
How did you come up with this default value? There's an _old_ rule of thumb for fan power where one can get an estimate by assuming 400 cfm/ton and 0.365 W/cfm. Perhaps we should use that and use `logging` to let the user know what fan power was assumed.

2024-04-29 16:15 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        fan_power=7000,
OK. Let's use a input power as 0.365*400*ref_cap for now.

2024-04-29 16:21 UTC, wanhanlong1130 commented on copper/data/equipment_references.json
> +            "cooling_coil_inlet_air_wet_bulb": 19.44
changed

2024-05-06 22:20 UTC, lymereJ requested changes
@wanhanlong1130 - I noticed that you asked for my review but I think that some of the comments had not all been addressed.

2024-05-06 22:20 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        self.ref_net_cap = ref_net_cap
Duplicate.

2024-05-06 22:20 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        self.ref_cap = ref_gross_cap
Let's perhaps get rid of `ref_cap` and use `ref_gross_cap` and `ref_net_cap` throughout when applicable.

2024-05-06 22:20 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                    fan_power = 0.28434517 * ref_net_cap * 400 * 0.365 / 1000
Let's add a log for the default fan power.

2024-05-06 22:20 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        if ref_gross_cap == None:
We should probably add a test for this input validation.

2024-05-06 22:20 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                    fan_power = 0.28434517 * ref_net_cap * 400 * 0.365 / 1000
Let's document that this is 400 cfm/ton and 0.365 W/cfm. We could cite equation 11.1 from AHRI 210/240 as the source for the latter, see [here](https://www.ahrinet.org/system/files/2023-10/AHRI%20Standard%20211-241-0B1B-2021%20%28SI%29%20%281%29.pdf). Not really something that we can cite but here's an interesting discussion about the former, [here](https://tranecds.custhelp.com/app/answers/detail/a_id/918/~/rule-of-thumb-calculations-%28400-cfm%2Fton%29).

2024-05-06 22:20 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        ref_cap_unit,
We probably don't need this anymore since we have `ref_gross_cap` and `ref_net_cap`

2024-05-06 22:20 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +            self.ref_cap * tot_cap_temp_mod_fac * tot_cap_flow_mod_fac - self.fan_power
I think that this should be `ref_gross_cap`, not `ref_cap`

2024-05-06 22:20 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        rated_cop = self.full_eff
We need to clarify if this is a net a gross input. We should probably have similar inputs as for the capacity, or, perhaps a single input that could be used by the user to specify if `full_eff` is net or gross.

2024-05-06 22:20 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +                ][std]["outdoor_unit_inlet_air_dry_bulb_reduced"]
I'm not sure if we actually need all of that, could we just that up from the `equipment_references` JSON file?

2024-05-06 23:07 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        self.ref_net_cap = ref_net_cap
Thanks for checking

2024-05-06 23:09 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        self.ref_cap = ref_gross_cap
fixed

2024-05-06 23:11 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +                    fan_power = 0.28434517 * ref_net_cap * 400 * 0.365 / 1000
added

2024-05-06 23:13 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +            self.ref_cap * tot_cap_temp_mod_fac * tot_cap_flow_mod_fac - self.fan_power
remove ref_cap

2024-05-06 23:13 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        ref_cap_unit,
remove cap_unit

2024-05-06 23:14 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +                ][std]["outdoor_unit_inlet_air_dry_bulb_reduced"]
move 0.444, 5, and 30 to json file? We can discuss more next meeting

2024-05-06 23:15 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +                    fan_power = 0.28434517 * ref_net_cap * 400 * 0.365 / 1000
added

2024-05-06 23:15 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        if ref_gross_cap == None:
def test_calc_eff_ect_error(self):
            ##############
            # Todo test case for error outputs
            pass
       
I set a place holder there for later development

2024-05-06 23:24 UTC, wanhanlong1130 commented
@lymereJ I added place holder for other test cases. I think we need more testing cases there, not only invalid capacity inputs but also may other cases. I will develop that later.

2024-05-17 16:26 UTC, wanhanlong1130 commented
@lymereJ I've made previous comments as resolved; please take a final check - if it's good, I will merge pull request. I also added an issue to add test cases in the future.

2024-05-20 15:57 UTC, lymereJ requested changes
Looks good, a few minor things before we merge it!

2024-05-20 15:57 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        full_eff,
I think that we also need a qualified here, is the efficiency gross or net? Perhaps we could do like for the capacity.

2024-05-20 15:57 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        part_eff=0,
Same comment as above.

2024-05-20 15:57 UTC, lymereJ commented on copper/unitarydirectexpansion.py
> +        if self.model == "simplified_bf":
We should probably log an error for now when the model is something other than `simplified_bf`.

2024-05-20 23:31 UTC, wanhanlong1130 commented on copper/unitarydirectexpansion.py
> +        if self.model == "simplified_bf":
Update a ifelse check.

2024-05-20 23:33 UTC, wanhanlong1130 commented
@lymereJ Just update; plz double-check.

2024-05-28 18:03 UTC, lymereJ commented
Thanks! Merging now.

2024-05-28 18:03 UTC, merged